[workspace]
authors = ["Nhật Minh <mail@dhnm.dev>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "hello_mojo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.4.0.dev2025060513,<26"
pygame = ">=2.6.1,<3"
